trigger:
- main

pool:
  name: RamAgentPool

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK 6.0'
  inputs:
    packageType: 'sdk'
    version: '6.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet Packages'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build Project'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- powershell: |
    Remove-Module -Name * -ListAvailable | Remove-Module -Force
  displayName: 'Clear PowerShell Module Cache'

- script: |
    if dotnet tool list -g | grep -q dotnet-format; then
      dotnet tool uninstall -g dotnet-format
    fi
  displayName: 'Uninstall existing dotnet-format if installed'

- task: DotNetCoreCLI@2
  displayName: 'Install dotnet-format'
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install -g dotnet-format'

- task: DotNetCoreCLI@2
  displayName: 'Run .editorconfig checks'
  inputs:
    command: 'custom'
    custom: 'format'
    arguments: '--verify-no-changes'
    workingDirectory: '$(Agent.ToolsDirectory)/dotnet-tools/.store/dotnet-format/*/dotnet-format/*/tools/net6.0/any/'
  continueOnError: false # This will fail the pipeline if there are any formatting issues

- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests'
  inputs:
    command: 'test'
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --no-build'
