trigger:
- main

pool:
  Name: RamAgentPool
  demands:
  - Agent.Name -equals RamAgent

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: dotnet restore
  displayName: 'Restore dependencies'

- script: dotnet build --configuration Release
  displayName: 'Build solution'

- script: dotnet test --no-build --verbosity normal
  displayName: 'Run unit tests'
