trigger:
- main

pool:
  name: RamAgentPool

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK 6.0'
  inputs:
    packageType: 'sdk'
    version: '6.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet Packages'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build Project'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- script: |
    export PATH="$PATH:/home/vsts/.dotnet/tools"
    if dotnet tool list -g | grep -q dotnet-format; then
      echo 'dotnet-format already installed'
    else
      dotnet tool install -g dotnet-format
    fi
  displayName: 'Ensure dotnet-format is installed'

- script: |
    /home/vsts/.dotnet/tools/dotnet-format --verify-no-changes
  displayName: 'Run .editorconfig checks'
  continueOnError: false # This will fail the pipeline if there are any formatting issues

- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests'
  inputs:
    command: 'test'
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --no-build'
