trigger:
- main

pool:
  name: RamAgentPool

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK 6.0'
  inputs:
    packageType: 'sdk'
    version: '6.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet Packages'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build Project'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Install dotnet-format'
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install -g dotnet-format'

- script: echo '##vso[task.setvariable variable=PATH]$(PATH):$(AGENT_TOOLSDIRECTORY)/dotnet-tools'
  displayName: 'Add dotnet-format to PATH'

- task: DotNetCoreCLI@2
  displayName: 'Run .editorconfig checks'
  inputs:
    command: 'custom'
    custom: 'format'
    arguments: '--verify-no-changes'
  continueOnError: false # This will fail the pipeline if there are any formatting issues

- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests'
  inputs:
    command: 'test'
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --no-build'
